"""Put a GENERATED puddle take (a close top-down patch of the oak) into the scripted Louvre floor (gallery_floor.py).

Built 2026-10-05 for S1-GAL-PUDDLE-RETURN (Homie: the puddle should "appear as if water was dropping on it and then
slowly, slowly building… hyper-real"). The take is a 3.0 x 1.69 m patch of the chosen floor plate, centred on the
spill (x 0, 1.0 m out from CENTRE), generated by Seedance from that patch (prompts/S1-GAL-PUDDLE-RETURN.txt).
Everything outside the water stays the scripted floor pixel for pixel; only the water's change is carried over:

1. ALIGN: one affine per take, take -> the reference patch, by ECC on the patch's outer ring (no water lands there).
   Seedance reframes by ~1-3% but holds it through a take (v1: identical at frame 0, middle and last). In References
   mode the plate is only a loose guide: v2 REDREW the floor (other planks), ECC finds nothing, identity is used.
2. CHANGE: ratio = aligned frame / the take's own dry frames (the mean of the first --dry-frames, before the first
   drop). 1.0 where nothing changed; darker wet wood, glints and (later) the glow where the water is.
3. MASK: where the ratio departs from 1 (blurred, dilated, feathered), accumulated over time (the water only grows,
   so the mask never flickers off between ripples); feathered to 0 at the patch border.
4. APPLY: the floor patch region of --base (the dry lit floor, or VANISH's last frame with its faint damp ghost) x
   (1 + mask * (ratio - 1)). The patch is from the same plate the floor is built from, so this is the take relit to
   the floor's light. Written as ProRes 422 HQ q2 (yuv422p10le), 24 fps, with the take's own sound (standing rule).

NOISE (2026-10-05, the dark Versailles floor): on dark oak Seedance's frame-to-frame tone shimmer is ~10x the pale oak's
   in ratio terms (v4: ~10% of DRY pixels over the old fixed 0.03; whole panels joined the pool). So every ratio is first
   divided by its own exposure drift (the median ratio on the patch's outer 8% band, where the water never reaches) and the
   threshold is max(base, 3 x the band's 95th percentile) per frame (noise_floor()). On pale oak that stays at the base.

5. --glimmer (Homie, 2026-10-05: "a glimmer on the edges… like a portal has glowing edges, but… subtle", teal): the pool's
   waterline traced per frame from the same ratio, a thin teal rim travelling slowly round it (glimmer()); --hold N keeps
   the last water frame still with the glimmer moving (loops every --loop s); --dark = the blackout floor, rim the only light.

  python tools/puddle_comp.py TAKE.mp4 --patch-geom patch_geom.json --ref REF_PATCH.png --dry FLOOR_PLATE.png
         --out OUT.mov [--size 1920x1080] [--base dry|vanish] [--dry-frames 4] [--start S] [--end S] [--ease-src S]
         [--check SHEET.jpg]
         [--glimmer --glow-start S --glow-ramp S --gain G --loop S --hold S] [--dark]
Needs numpy, opencv, Pillow, ffmpeg (and tools/gallery_floor.py beside it).
"""
import argparse
import json
import os
import subprocess
import sys

import cv2
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gallery_floor as gf  # noqa: E402


def probe(p):
    j = json.loads(subprocess.check_output(['ffprobe', '-v', 'error', '-select_streams', 'v:0', '-count_frames',
                                            '-show_entries', 'stream=width,height,nb_read_frames', '-of', 'json', p]))
    s = j['streams'][0]
    return int(s['width']), int(s['height']), int(s['nb_read_frames'])


def frames(p, w, h):
    """Yield float32 RGB frames 0..1 at full bit depth (rgb48)."""
    pr = subprocess.Popen(['ffmpeg', '-v', 'error', '-i', p, '-f', 'rawvideo', '-pix_fmt', 'rgb48le', '-'],
                          stdout=subprocess.PIPE)
    n = w * h * 3 * 2
    while True:
        b = pr.stdout.read(n)
        if len(b) < n:
            break
        yield np.frombuffer(b, np.uint16).reshape(h, w, 3).astype(np.float32) / 65535.0
    pr.wait()


def align_warp(take_mean, ref):
    """ECC affine (take -> ref) on the outer ring of the patch."""
    H, W = ref.shape[:2]
    ring = np.ones((H, W), np.uint8)
    ring[int(H * .2):int(H * .8), int(W * .25):int(W * .75)] = 0
    g = lambda a: cv2.cvtColor(a.astype(np.float32), cv2.COLOR_RGB2GRAY)
    w = np.eye(2, 3, dtype=np.float32)
    _, w = cv2.findTransformECC(g(ref), g(take_mean), w, cv2.MOTION_AFFINE,
                                (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 300, 1e-7), ring, 5)
    return w


def noise_floor(ratio, base, sigma, wet=None):
    """(ratio with the frame's exposure drift divided out, threshold): both from the patch's outer 8% band, minus any
    known water (wet: the water found so far, dilated; v6's pool reached the band at 7.5 s and the threshold ran away).
    thr = max(base, 3 x p95 of the band's blurred |ratio - 1|)."""
    H, W = ratio.shape[:2]
    band = np.zeros((H, W), bool)
    by, bx = max(1, int(.08 * H)), max(1, int(.08 * W))
    band[:by] = band[-by:] = True
    band[:, :bx] = band[:, -bx:] = True
    if wet is not None:
        clear = band & ~cv2.dilate(wet.astype(np.uint8), np.ones((max(3, W // 40),) * 2, np.uint8)).astype(bool)
        if clear.sum() > 0.3 * band.sum():
            band = clear
    ratio = ratio / np.median(ratio[band], axis=0)
    lum = cv2.GaussianBlur(np.abs(ratio.mean(2) - 1), (0, 0), sigma)
    return ratio, max(base, 3.0 * float(np.percentile(lum[band], 95)))


def water_mask(ratio_hi, thr, close_px):
    """The pool at the take's own resolution: where the take departs from its dry frames, closed, holes filled,
    the largest piece only (the pool; stray beads get no rim)."""
    lum = cv2.GaussianBlur(np.abs(ratio_hi.mean(2) - 1), (0, 0), 3)
    b = (lum > thr).astype(np.uint8)
    b = cv2.morphologyEx(b, cv2.MORPH_CLOSE, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (close_px, close_px)))
    pad = np.pad(b, 1)                                       # a dry border, so the fill always starts outside the water
    cv2.floodFill(pad, np.zeros((pad.shape[0] + 2, pad.shape[1] + 2), np.uint8), (0, 0), 2)
    b = (pad[1:-1, 1:-1] != 2).astype(np.uint8)              # everything the outside can't reach = water + its holes
    # open: cut off the stray beads touching the rim and thin leaks along plank seams (v2: one ran down a seam)
    b = cv2.morphologyEx(b, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (close_px, close_px)))
    n, lab, st, _ = cv2.connectedComponentsWithStats(b, 8)
    if n <= 1:
        return np.zeros_like(b)
    k = 1 + int(np.argmax(st[1:, cv2.CC_STAT_AREA]))
    b = (lab == k).astype(np.float32)
    return (cv2.GaussianBlur(b, (0, 0), 3) > 0.5).astype(np.uint8)   # a smooth waterline, not pixel stairs


# the glimmer's travelling waves round the rim: (cycles round the pool, cycles per loop, weight); all integers, so the
# pattern is periodic in angle and over --loop seconds (a hold of a whole number of loops cycles seamlessly)
WAVES = [(3, 1, 1.0), (5, -2, 0.7), (8, 3, 0.5), (13, -4, 0.35)]


def glimmer(mask, ratio_hi, t, loop, ppm, phases):
    """A thin teal light ON the waterline (Homie 2026-10-05: "a glimmer on the edges… like a portal has glowing edges,
    but obviously something subtle"): a crisp core just inside the meniscus, a hairline catch on the wood just outside,
    a faint bloom into the water; broken into bright segments that travel slowly round the rim (never fully out),
    plus the take's own surface highlights near the edge sparkling teal."""
    if mask.sum() < 50:
        return np.zeros(mask.shape, np.float32)
    sm = cv2.GaussianBlur(mask.astype(np.float32), (0, 0), 1.5) > 0.5
    d_in = cv2.distanceTransform(sm.astype(np.uint8), cv2.DIST_L2, 5) / ppm
    d_out = cv2.distanceTransform((~sm).astype(np.uint8), cv2.DIST_L2, 5) / ppm
    core = np.exp(-(d_in / 0.006) ** 2) * sm
    catch = 0.55 * np.exp(-(d_out / 0.004) ** 2) * (~sm)
    bloom = 0.16 * np.exp(-d_in / 0.035) * sm
    ys, xs = np.nonzero(sm)
    cy, cx = ys.mean(), xs.mean()
    yy, xx = np.mgrid[0:mask.shape[0], 0:mask.shape[1]].astype(np.float32)
    th = np.arctan2(yy - cy, xx - cx)
    mod = sum(w * (0.5 + 0.5 * np.cos(n * th - 2 * np.pi * m * t / loop + ph)) for (n, m, w), ph in zip(WAVES, phases))
    mod = mod / sum(w for _, _, w in WAVES)
    mod = 0.22 + 0.78 * np.clip((mod - 0.35) / 0.5, 0, 1) ** 1.8
    hl = np.clip(ratio_hi.mean(2) - 1.03, 0, 0.3) * np.exp(-d_in / 0.03) * sm * 2.5
    return ((core + catch + bloom) * mod + hl).astype(np.float32)


def arrival_field(seeds, domain, dry_hi, step=4, seed=11):
    """FLOW (Homie 2026-10-05: "flowing outwards like it naturally does rather than just the blob scaling up"): when the
    water reaches each point of the final pool, from the drops' bead. A weighted distance (8-neighbour relaxation at
    1/step resolution), cheaper along the parquet's seams (water runs ahead in them) and uneven by a low-frequency
    noise (lobes and fingers). Normalised to 1 at the farthest point of the pool; inf outside it."""
    H, W = domain.shape
    h, w = H // step, W // step
    dom = cv2.resize(domain.astype(np.uint8), (w, h), interpolation=cv2.INTER_NEAREST) > 0
    sd = cv2.resize(seeds.astype(np.uint8), (w, h), interpolation=cv2.INTER_NEAREST) > 0
    if not sd.any():
        ys, xs = np.nonzero(dom)
        sd[int(ys.mean()), int(xs.mean())] = True
    lum = cv2.resize(cv2.cvtColor(dry_hi.astype(np.float32), cv2.COLOR_RGB2GRAY), (w, h), interpolation=cv2.INTER_AREA)
    seam = cv2.morphologyEx(lum, cv2.MORPH_BLACKHAT, cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5)))
    seam = np.clip(seam / (np.percentile(seam, 99) + 1e-6), 0, 1)
    rng = np.random.default_rng(seed)
    def octave(sig):
        nz = cv2.GaussianBlur(rng.normal(0, 1, (h, w)).astype(np.float32), (0, 0), sig)
        return (nz - nz.mean()) / (nz.std() + 1e-6)
    # big lobes + small fingers; the seams only a little faster (v1 1.6: the front ran along them in straight lines)
    noise = 0.35 * octave(max(w, h) / 14) + 0.15 * octave(max(w, h) / 60)
    cost = 1.0 / np.clip(1.0 + 0.2 * seam + noise, 0.4, None)
    T = np.full((h, w), np.inf, np.float32)
    T[sd & dom] = 0
    T[sd & ~dom] = 0
    steps = [(dy, dx, np.hypot(dy, dx)) for dy in (-1, 0, 1) for dx in (-1, 0, 1) if dy or dx]
    for _ in range(4 * (h + w)):
        old = T.copy()
        for dy, dx, d in steps:
            sh = np.full_like(T, np.inf)
            sh[max(dy, 0):h + min(dy, 0), max(dx, 0):w + min(dx, 0)] = \
                T[max(-dy, 0):h + min(-dy, 0), max(-dx, 0):w + min(-dx, 0)]
            T = np.minimum(T, sh + cost * d)
        T[~dom] = np.inf
        T[sd] = 0
        if np.array_equal(old, T):
            break
    fin = np.isfinite(T)
    T[dom & ~fin] = T[fin].max()        # pockets the relaxation never reached fill last (v1: holes = teal dots)
    fin = np.isfinite(T)
    T = T / (np.percentile(T[fin], 99.5) + 1e-6)
    T[~fin] = 9.0
    T = np.where(dom, cv2.GaussianBlur(np.minimum(T, 1.5), (0, 0), 3.0), 9.0)   # a rounded front, not stair-steps
    return cv2.resize(T, (W, H), interpolation=cv2.INTER_LINEAR)


def debubble(ratio_hi, mask, ppm, frame):
    """Homie 2026-10-05: no bubbles on the settled pool. The 'marbles' (domed beads sitting on the water, ~4-8 cm) are
    found as small round specular blobs in the take's own picture (Hough circles; the ratio is useless here: the
    laylight's reflection reaches 9x) inside the pool, and filled in the ratio by a normalised blur of their
    surroundings (colour-safe: per-channel inpainting left coloured specks, v1)."""
    g = (np.clip(frame.mean(2), 0, 1) * 255).astype(np.uint8)
    c = cv2.HoughCircles(cv2.GaussianBlur(g, (5, 5), 1.2), cv2.HOUGH_GRADIENT, dp=1, minDist=int(0.03 * ppm),
                         param1=60, param2=18, minRadius=int(0.01 * ppm), maxRadius=int(0.04 * ppm))
    inner = cv2.erode(mask.astype(np.uint8), np.ones((int(0.06 * ppm),) * 2, np.uint8)) > 0
    hole = np.zeros(mask.shape, np.float32)
    found = []
    for x, y, r in (c[0] if c is not None else []):
        if inner[int(y), int(x)]:
            cv2.circle(hole, (int(x), int(y)), int(r * 1.5) + 3, 1.0, -1)
            found.append((int(x), int(y), int(r)))
    if not found:
        print('debubble: none found', flush=True)
        return ratio_hi
    sig = 0.02 * ppm
    keep = 1 - hole
    fill = cv2.GaussianBlur(ratio_hi * keep[..., None], (0, 0), sig) / (cv2.GaussianBlur(keep, (0, 0), sig)[..., None] + 1e-4)
    soft = cv2.GaussianBlur(hole, (0, 0), 2)[..., None]
    print(f'debubble: {len(found)} beads filled {found}', flush=True)
    return ratio_hi * (1 - soft) + fill * soft


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('take')
    ap.add_argument('--patch-geom', required=True)
    ap.add_argument('--ref', required=True)
    ap.add_argument('--dry', required=True, help='the floor plate gallery_floor.py is built from')
    ap.add_argument('--out', required=True)
    ap.add_argument('--size', default='1920x1080')
    ap.add_argument('--base', choices=['dry', 'vanish'], default='vanish')
    ap.add_argument('--dark', action='store_true', help='the blackout floor (gallery_floor dark): only the glimmer reads')
    ap.add_argument('--dry-frames', type=int, default=4)
    ap.add_argument('--thresh', type=float, default=0.025)
    ap.add_argument('--check', default=None)
    ap.add_argument('--start', type=float, default=0.0, help='skip to this time (s) of the take (renders from here)')
    ap.add_argument('--end', type=float, default=None, help='stop at this time (s): v2 spreads past the patch after ~9.7 s')
    ap.add_argument('--glimmer', action='store_true', help='the teal rim light on the waterline')
    ap.add_argument('--glow-start', type=float, default=0.0, help='take time (s) the glimmer starts to rise')
    ap.add_argument('--glow-ramp', type=float, default=2.0)
    ap.add_argument('--gain', type=float, default=None, help='glimmer strength (default 0.55 lit, 1.1 dark)')
    ap.add_argument('--loop', type=float, default=8.0, help='the glimmer pattern repeats every LOOP seconds')
    ap.add_argument('--ease-src', type=float, default=0.0,
                    help='the last S s of the take (before --end) are slowed to a stop: stretched x3 with a cubic ease-out '
                         '(speed matched at the join). v6 kept spreading past the patch: the stop is made here')
    ap.add_argument('--flow-from', type=float, default=None,
                    help='FLOW: play the take to S (the drops and the pause), then reveal the pool at --end by a flowing '
                         'front (arrival_field) over --flow-s, ease-out with small surges; the glimmer rides the front')
    ap.add_argument('--flow-s', type=float, default=4.0)
    ap.add_argument('--debubble', action='store_true', help='inpaint the small spheres sitting on the settled pool')
    ap.add_argument('--hold', type=float, default=0.0, help='after the last frame, hold the pool still for N s, the '
                                                            'glimmer still moving (a whole number of --loop cycles loops)')
    a = ap.parse_args()

    size = tuple(map(int, a.size.split('x')))
    geom = json.load(open(a.patch_geom))
    pw_m, ph_m = geom['patch_m']
    cx_m, cd_m = geom['centre_m']
    tw, th, n = probe(a.take)
    if a.end:
        n = min(n, int(round(a.end * 24)))
    i_start = int(round(a.start * 24))
    ref = cv2.cvtColor(cv2.imread(a.ref), cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0
    ref = cv2.resize(ref, (tw, th), interpolation=cv2.INTER_AREA)
    gain = a.gain if a.gain is not None else (1.1 if a.dark else 0.55)   # in the blackout it is the only light
    ppm_take = tw / pw_m
    phases = np.random.default_rng(7).uniform(0, 2 * np.pi, len(WAVES))

    # 1. the warp, from the dry opening frames
    it = frames(a.take, tw, th)
    first = [next(it) for _ in range(a.dry_frames)]
    dry_mean = np.mean(first, 0)
    try:
        W = align_warp(dry_mean, ref)
    except cv2.error:
        # the take redrew the floor (v2: other plank breaks, other grain): nothing to align to. The change is still
        # measured against the take's OWN dry frames, so it lands on the plate; the frame centre = the spill centre.
        W = np.eye(2, 3, dtype=np.float32)
        print('ECC found no match (the take redrew the floor): identity warp', flush=True)
    warp = lambda f: cv2.warpAffine(f, W, (tw, th), flags=cv2.INTER_LINEAR | cv2.WARP_INVERSE_MAP,
                                    borderMode=cv2.BORDER_REFLECT)
    print('warp (take -> ref):', np.round(W, 4).tolist(), flush=True)
    dry_hi = warp(dry_mean)

    # the floor and the patch's place on it
    F = gf.Floor(gf.load(a.dry), size)
    level = float(F.sd.max()) + 0.01 if a.base == 'vanish' else None
    base = F.lit(level, dark=a.dark)
    rw, rh = int(round(pw_m * F.ppm)), int(round(ph_m * F.ppm))
    c0 = int(round((cx_m + gf.ENV_W / 2) * F.ppm - rw / 2))
    r0 = int(round(F.y0 + cd_m * F.ppm - rh / 2))
    print(f'floor {size}, ppm {F.ppm:.1f}, patch region x{c0} y{r0} {rw}x{rh}', flush=True)
    small = lambda f: cv2.resize(f, (rw, rh), interpolation=cv2.INTER_AREA)
    dry_s = small(dry_hi)
    # patch border feather: 0 at the edge, 1 from 8% in
    yy, xx = np.mgrid[0:rh, 0:rw].astype(np.float32)
    edge = np.minimum(np.minimum(xx, rw - 1 - xx) / (0.08 * rw), np.minimum(yy, rh - 1 - yy) / (0.08 * rh))
    edge = gf.ease(np.clip(edge, 0, 1))
    k = max(3, int(rw * 0.012) | 1)
    acc = np.zeros((rh, rw), np.float32)
    pool = np.zeros((th, tw), np.uint8)
    poolf = np.zeros((th, tw), np.float32)

    n_hold = int(round(a.hold * 24))
    n_src = int(round(a.ease_src * 24))
    n_out = 3 * n_src            # cubic ease-out: starting speed 3 * (n_src - 1) / n_out ~ the take's own
    n_ff = int(round(a.flow_from * 24)) if a.flow_from is not None else None
    n_flow = int(round(a.flow_s * 24)) if n_ff is not None else 0
    total = (n_ff - i_start + n_flow + n_hold) if n_ff is not None else (n - i_start + (n_out - n_src) + n_hold)
    dur = f'{total / 24:.4f}'   # the take's sound, padded with silence through the hold, cut to the picture
    enc = subprocess.Popen(['ffmpeg', '-v', 'error', '-y', '-f', 'rawvideo', '-pix_fmt', 'rgb48le',
                            '-s', f'{size[0]}x{size[1]}', '-r', '24', '-i', '-', '-ss', f'{i_start / 24:.4f}', '-i', a.take,
                            '-map', '0:v', '-map', '1:a?', '-c:v', 'prores_ks', '-profile:v', '3', '-qscale:v', '2',
                            '-pix_fmt', 'yuv422p10le', '-c:a', 'pcm_s24le', '-af', f'apad=whole_dur={dur}',
                            '-t', dur, a.out], stdin=subprocess.PIPE)
    picks = set((i_start + np.linspace(0, total - 1, 8)).astype(int).tolist()) if a.check else set()
    sheet = []
    last = {}

    def render(i, f=None, state=None):
        """i = take frame index (past n during the hold); f = the take frame, or None to reuse the last one;
        state = (ratio, ratio_hi, mm, pool) injected by the FLOW."""
        nonlocal acc, pool
        if state is not None:
            last.update(ratio=state[0], ratio_hi=state[1], mm=state[2])
            pool = state[3]
        elif f is not None:
            hi = warp(f)
            ratio_hi, thr_hi = noise_floor((hi + 0.01) / (dry_hi + 0.01), 0.03, 3, pool)
            s = small(hi)
            sig = max(1.0, rw / 900)
            ratio, thr = noise_floor((s + 0.01) / (dry_s + 0.01), a.thresh, sig, acc > 0.5)
            lum = cv2.GaussianBlur(np.abs(ratio.mean(2) - 1), (0, 0), sig)
            m = np.clip((lum - thr) / thr, 0, 1)
            m = cv2.dilate(m, np.ones((k, k), np.uint8))
            acc = np.maximum(acc, cv2.GaussianBlur(m, (0, 0), k / 2))
            if a.glimmer:   # smoothed over ~4 frames: steady, but follows the waterline (an OR kept old seam leaks)
                poolf[:] = poolf * 0.7 + water_mask(ratio_hi, thr_hi, 25) * 0.3
                pool = (poolf > 0.5).astype(np.uint8)
            last.update(ratio=ratio, ratio_hi=ratio_hi)
        ratio, ratio_hi = last['ratio'], last['ratio_hi']
        if i < i_start:
            return None
        mm = ((last['mm'] if 'mm' in last else acc) * edge)[..., None]
        out = base.copy()
        reg = base[r0:r0 + rh, c0:c0 + rw] * (1 + mm * (ratio - 1))
        if a.glimmer:
            tt = i / 24
            g = gf.ease((tt - a.glow_start) / max(a.glow_ramp, 1e-3))
            if g > 0:
                gl = small(glimmer(pool, ratio_hi, tt, a.loop, ppm_take, phases)[..., None].repeat(3, 2))[..., 0]
                reg = reg + (gl * edge * g * gain)[..., None] * gf.TEAL
        out[r0:r0 + rh, c0:c0 + rw] = reg
        out = np.clip(out, 0, 1)
        enc.stdin.write((out * 65535 + 0.5).astype(np.uint16).tobytes())
        if i in picks:
            sheet.append((i, out[max(0, r0 - 40):r0 + rh + 40, max(0, c0 - 80):c0 + rw + 80].copy()))
        return True

    i = 0
    for f in first:
        render(i, f); i += 1
    src, buf = a.dry_frames, []
    if n_ff is not None:
        for f in it:                                   # the take: the drops, the beads, the pause
            if src >= n_ff:
                break
            render(i, f); i += 1; src += 1
        r_last, rh_last, acc_last, seeds = last['ratio'], last['ratio_hi'], acc.copy(), pool.copy()
        tail = []
        for f in it:                                   # read on to --end: the final pool's shape and surface
            src += 1
            if src > n - 3:
                tail.append(warp(f))
            if src >= n:
                break
        hi = np.mean(tail, 0)
        rf_hi, thr_f = noise_floor((hi + 0.01) / (dry_hi + 0.01), 0.03, 3)
        M = water_mask(rf_hi, thr_f, 25)
        M = cv2.morphologyEx(M, cv2.MORPH_CLOSE, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (61, 61)))  # seam inlets
        if a.debubble:
            rf_hi = debubble(rf_hi, M, ppm_take, hi)
        Tf = arrival_field(seeds > 0, cv2.dilate(M, np.ones((5, 5), np.uint8)) > 0, dry_hi)
        Msoft = cv2.GaussianBlur(M.astype(np.float32), (0, 0), 1.5)
        prev_u = 0.0
        for j in range(n_flow):
            tau = (j + 1) / n_flow
            u = 1.04 * (1 - (1 - tau) ** 2.2) + 0.025 * np.sin(2 * np.pi * 5 * tau) * (1 - tau)
            u = prev_u = max(prev_u, u)                # surges, never backwards
            Rv = np.clip((u - Tf) / 0.02, 0, 1)
            Rv = cv2.GaussianBlur(Rv * Rv * (3 - 2 * Rv), (0, 0), 1.5) * np.maximum(Msoft, (seeds > 0) * 1.0)
            c = gf.ease(min(1.0, j / 12))              # the bead's surface hands over to the settled pool's
            r_hi = (1 - c) * rh_last + c * rf_hi
            front = 4 * Rv * (1 - Rv) * (1 - gf.ease(tau)) * 0.16   # a bright meniscus on the advancing edge
            ratio_hi_j = 1 + Rv[..., None] * (r_hi - 1) + front[..., None]
            mm_j = np.maximum(small(Rv), acc_last * (1 - c))
            render(i, state=(small(ratio_hi_j), ratio_hi_j, mm_j, (Rv > 0.5).astype(np.uint8))); i += 1
        it = iter(())
    for f in it:
        if src >= n:
            break
        if src >= n - n_src:
            buf.append(f.astype(np.float16))   # the stretch, blended below
        else:
            render(i, f); i += 1
        src += 1
    for j in range(n_out if buf else 0):
        u = j / max(n_out - 1, 1)
        q = (len(buf) - 1) * (1 - (1 - u) ** 3)
        q0 = int(q); q1 = min(q0 + 1, len(buf) - 1); w = q - q0
        render(i, buf[q0].astype(np.float32) * (1 - w) + buf[q1].astype(np.float32) * w); i += 1
    for _ in range(n_hold):
        render(i); i += 1
    enc.stdin.close()
    enc.wait()
    print('frames', i - i_start, f'(take {i_start}-{(n_ff or n) - 1}, flow {n_flow}, last {n_src} eased to {n_out if buf else 0} + hold {n_hold})'
          ' ->', a.out, flush=True)
    if a.check and sheet:
        tiles = [cv2.cvtColor((np.clip(cv2.resize(t, (640, int(640 * t.shape[0] / t.shape[1]))), 0, 1) * 255)
                              .astype(np.uint8), cv2.COLOR_RGB2BGR) for _, t in sheet]
        for (j, _), t in zip(sheet, tiles):
            cv2.putText(t, f'{j / 24:.2f}s', (8, 22), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)
        rows = [np.hstack(tiles[r * 4:(r + 1) * 4]) for r in range(len(tiles) // 4)]
        cv2.imwrite(a.check, np.vstack(rows))


if __name__ == '__main__':
    main()
